name: Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

env:
  OIDC_IAM_ROLE_ARN: ${{ secrets.OIDC_IAM_ROLE_ARN }}
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

# 同時実行すると CREATE_IN_PROGRESS や UPDATE_IN_PROGRESS 状態で cdk deploy を行う可能性があるため抑止する
concurrency:
  group: "rag-examle-cloudformation"
  cancel-in-progress: false

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [22.x]

    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.OIDC_IAM_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]
          - args: [--global, aws-cdk, esbuild]

    - name: deploy
      working-directory: ./cdk
      run: |
        cdk deploy \
          -c oai-endpoint=${{ secrets.AZURE_OPENAI_API_INSTANCE_NAME }} \
          -c oai-api-key=${{ secrets.AZURE_OPENAI_API_KEY }} \
          -c oai-deploy=${{ secrets.AZURE_OPENAI_API_DEPLOYMENT_NAME }} \
          -c oai-api-version=${{ vars.AZURE_OPENAI_API_VERSION }} \
          -c langfuse-endpoint=${{ secrets.LANGFUSE_ENDPOINT }} \
          -c langfuse-public-key=${{ secrets.LANGFUSE_PUBLIC_KEY }} \
          -c langfuse-secret-key=${{ secrets.LANGFUSE_SECRET_KEY }} \
          -c langsmith-api-key=${{ secrets.LANGCHAIN_API_KEY }} \
          -c langsmith-project=${{ secrets.LANGCHAIN_PROJECT }} \
          -c pinecone-index=${{ vars.PINECONE_INDEX }} \
          -c pinecone-api-key=${{ secrets.PINECONE_API_KEY }}
